Split and update list of monitoring items
cksource/cksource-monitoring pull request #25
Opened 2024-09-05 12:50 UTC by vokiel

## Changelog

```
Feature: Split and update list of monitoring items

Added definitions for monitoring items, split into separate file.

Refs: https://github.com/cksource/cksource-monitoring/issues/17
```

## Linked issues

Refs: https://github.com/cksource/cksource-monitoring/issues/17

---

2024-09-05 13:30 UTC, LukaszGudel commented on src/testsData.ts
Or move `testsDefinition.ts` to common, so that anybody who visits this repo will know exactly where to change/add tests. I feel like `testsData` and `testsDefinition` next to each other means almost the same 🤔

2024-09-05 13:44 UTC, dpawlowski-cksource commented on src/testsData.ts
> +	Tiugo: {
What do you think about splitting this file into at least 4 parts (4 files):
- TiugoTestData.json/ts
- CKSourceTestData.json/ts
- TinyTestData.json/ts
- ButterCMSTestData.json/ts

and import it there 🤔 ?

2024-09-05 13:44 UTC, dpawlowski-cksource commented on src/testsDefinition.ts
> +							console.log( entry );
```suggestion
```

2024-09-05 13:44 UTC, dpawlowski-cksource commented on src/testsDefinition.ts
> +					for ( const [ productGroup, entries ] of Object.entries( data ) ) {
```suggestion
					for ( const [ productGroup, (entries as IPingTestEntry[]) ] of Object.entries( data ) ) {
```

2024-09-05 13:44 UTC, dpawlowski-cksource commented on src/testsDefinition.ts
> +					for ( const [ productGroup, entries ] of Object.entries( data ) ) {
It should be possible if I'm not wrong ☝️

2024-09-05 13:44 UTC, dpawlowski-cksource commented on src/testsDefinition.ts
> +					data.forEach( entry => {
```suggestion
					data.forEach( entry as string => {
```

2024-09-05 13:49 UTC, vokiel commented on src/testsDefinition.ts
> +					for ( const [ productGroup, entries ] of Object.entries( data ) ) {
nope :disappointed: 

>  25:33  error  Parsing error: Array element destructuring pattern expected

2024-09-05 13:57 UTC, vokiel commented on src/testsDefinition.ts
> +					data.forEach( entry => {
:disappointed: 

> 43:35  error  Parsing error: ',' expected

2024-09-05 14:03 UTC, vokiel commented on src/testsData.ts
> +	Tiugo: {
Hmm, maybe better would be group it by test type, e.g:

*   `PingTestData.json/ts`
*   `DomainTestData.json/ts`
*   `CertificateTestData.json/ts`

As we will run them by type, not organization. E.g - ping every 1 minute, and cert/domain once per day. So we could then read only those files that tests will use - without need to load them all.

2024-09-05 14:40 UTC, dpawlowski-cksource commented on src/testsDefinition.ts
> +						for ( const entry of entries ) {
```suggestion
						for ( const entry of entries as IPingTestEntry[] ) {
```

2024-09-05 14:40 UTC, dpawlowski-cksource commented on src/testsDefinition.ts
> +					data.forEach( entry => {
```suggestion
					data.forEach( ( domain: string ) => {
```

so this way 😉

2024-09-05 14:40 UTC, dpawlowski-cksource commented on src/testsDefinition.ts
> +					data.forEach( entry => {
```suggestion
					data.forEach( ( url: string ) => {
```

2024-09-06 07:24 UTC, LukaszGudel requested changes
Important change requested before we can merge it. I didn't noticed it before, but we can't add all the tests to TESTS_DEFINITION just yet.

Also, could you make 2 small changes in index.ts file? This would be useful for our next steps and we will make sure that our triggers are working as expected.

Add event argument to the handler function and console.log it:
```
export const handler = async (event: unknown): Promise<string> => {
   console.log(event);
```

2024-09-06 07:24 UTC, LukaszGudel commented on src/testsDefinition.ts
> +					} );
Could you comment out `TESTS_DEFINITION.push` for domain and certificate tests? We can't merge it like this, as this would run all the tests every 1min and all at once, and we still need to use event data from triggers and improve test runner concurrency.

2024-09-06 10:07 UTC, LukaszGudel approved these changes

2024-09-06 10:20 UTC, merged