chore: Split test data into separate files.
cksource/cksource-monitoring pull request #28
Opened 2024-09-10 06:52 UTC by vokiel

## Changelog

```
chore: Split test data into separate files

Added description to readme.

Refs: https://github.com/cksource/cksource-monitoring/issues/17
```

## Linked issues

Refs: https://github.com/cksource/cksource-monitoring/issues/17

---

2024-09-10 07:21 UTC, LukaszGudel approved these changes

2024-09-10 07:47 UTC, dpawlowski-cksource reviewed
Added suggestion. But I submit review as `Comment` to not bleck merge if you want to do it later 🙂

2024-09-10 07:47 UTC, dpawlowski-cksource commented on README.md
> +All test resources are located in `src/data` folder. Split into separate test type files:
The division is ok 👌 but the only thing that is confusing for me is the `data` word. Sounds like some common thing that is used to send through REST API to the server 😛

TBH `testDefinitions` sounds better to me. Or just `tests` 🤔 

Currently, the folder structure is not intuitive. Maybe we can inspire with some other testing frameworks 🤔 ?

My ideas:
- Rename `src/tests` -> `src/testSuites`/`src/testTypes`/`src/testDefinitions` 🤔 ??
- Move `src/data/types.ts` to `src/types.ts`
- Rename `src/data` -> `src/tests`
- Move `testsData.ts` -> `tests/index.ts`

But please take a look at other test frameworks 🙏 or talk each other for best solution 🙂

2024-09-10 08:30 UTC, vokiel commented on README.md
> +All test resources are located in `src/data` folder. Split into separate test type files:
`testSuites` sounds good to me

2024-09-10 14:24 UTC, LukaszGudel approved these changes
Check/checks name used everywhere was strange at first but now I kinda like it, so 👍 from me 😄 

Just let's remember to sync merging this with PR in cs repo and also we would need to update alerts and dashboards in Grafana on-call.

2024-09-10 14:24 UTC, LukaszGudel commented on src/types.ts
WDYT about moving this to `common`?

2024-09-10 14:24 UTC, LukaszGudel commented on src/checks/index.ts
WDYT about renaming this to `getChecks.ts` or even moving it to common? I know that `common` isn't perfect either but this would separate the folder with checks definition from all the other internal logic for running these checks.

2024-09-10 14:29 UTC, dpawlowski-cksource approved these changes
TBH for me `test` vs `check` is almost the same 😛 Keep in mind that we plan to add a little more complex "tests/checks" for demo pages and butter CMS (test login, test if adding new page works, test if modifying new page works, etc.). I hope this name will still fit for it 😄

2024-09-10 14:40 UTC, LukaszGudel commented
One thing I noticed, we need to update circleCI config, line 39, as this is still using the old path to Dockerfile:
``` 
dockerfile_path: ./docker/tests-runner/Dockerfile
```

2024-09-10 15:08 UTC, vokiel commented on src/checks/index.ts
Good point

2024-09-11 06:58 UTC, dpawlowski-cksource commented on infrastructure/grafana/dashboards/buttercms---certificates-and-domains.json
> +              "expr": "increase(monitoring_check_fails_counter{check_name=\"certificate_expiration\", organization=\"ButterCMS\"}[72h])",
One request from me, by the way as you are changing metric names, can you rename `_counter` to `_count` 🙏  🙂 

It will prevent from displaying this warning in Grafana Dashboards 😄 👇 

<img width="489" alt="image" src="https://github.com/user-attachments/assets/9e1a1d64-3048-4a2c-9493-1b6e92e409de">

2024-09-11 07:06 UTC, dpawlowski-cksource requested changes
Remember about https://github.com/cksource/cksource-monitoring/blob/master/src/common/Metrics.ts#L60

2024-09-11 07:26 UTC, dpawlowski-cksource approved these changes

2024-09-11 07:28 UTC, merged